import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Maximize2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import './globals.css';
const pages=[['00page.png','추억의 표지','표지'],['0page.png','제26회 졸업기념','속표지'],['1page.png','그리운 우리 학교','학교'],['2page.png','고마운 선생님들','선생님'],['3page.png','우리 반의 얼굴들 · 하나','졸업생'],['4page.png','우리 반의 얼굴들 · 둘','졸업생'],['5page.png','우리 반의 얼굴들 · 셋','졸업생'],['6page.png','우리 반의 얼굴들 · 넷','졸업생'],['7page.png','함께 웃던 날들','학교생활']];
const photo=(file:string)=>`${import.meta.env.BASE_URL}album/${file}`;
function App(){const[current,setCurrent]=useState(0);const[open,setOpen]=useState(false);const[zoom,setZoom]=useState(false);const[heroView,setHeroView]=useState(false);const viewed=heroView?['화질복원.png','우리 반 단체사진']:pages[current];
const move=(delta:number)=>{setCurrent(i=>Math.max(0,Math.min(pages.length-1,i+delta)));setZoom(false)};
useEffect(()=>{if(!open||heroView)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,heroView]);
const show=(i:number)=>{setHeroView(false);setCurrent(i);setZoom(false);setOpen(true)};
return <><a className="skip" href="#album">앨범으로 바로 가기</a><div className="topline">1980학년도 · 제26회 졸업기념 <span>우리들의 이야기는, 여전히 이곳에.</span></div>
<header><a className="brand" href="#"><span className="seal">월학</span><span>월학국민학교<small>제26회 졸업생 추억 보관소</small></span></a><nav aria-label="주 메뉴"><a href="#school">우리 학교</a><a href="#album">졸업앨범</a><a href="#moments">그때 그 시절</a></nav><a className="header-link" href="#album">앨범 펼치기 <ArrowUpRight size={17}/></a></header>
<main><section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">기억 속 교문을 다시 열며</p><h1 id="hero-title">우리는 아직,<br/><em>그 교실에</em><br/>함께 있습니다.</h1><p className="intro">분필 냄새 나던 교실, 흙먼지 날리던 운동장.<br/>한 장의 사진을 펼치면<br/>그리운 얼굴들이 우리를 기다립니다.</p><a className="primary" href="#album"><BookOpen size={19}/> 우리의 졸업앨범 <ArrowRight size={19}/></a><div className="year"><span>1981</span><p>월학국민학교<br/>제26회 졸업생</p></div></div><div className="hero-photo"><span className="tape" aria-hidden="true"/><button className="photo-button" onClick={()=>{setHeroView(true);setZoom(false);setOpen(true)}} aria-label="우리 반 단체사진 크게 보기"><img src={photo('화질복원.png')} alt="교실 앞 계단에 함께 모인 월학국민학교 졸업생 단체사진" fetchPriority="high"/><span className="photo-enlarge"><Maximize2 size={17}/> 크게 보기</span></button><div className="caption"><span>참 반가운 얼굴들. 우리의 어린 날.</span><span>1981, 월학</span></div><div className="stamp" aria-hidden="true">졸업기념<br/><b>第 26 回</b><br/>1980 學年度</div></div></section>
<div className="motto" id="school"><span>그때의 교훈</span><p>부지런하고 <i>·</i> 참되고 <i>·</i> 정다운 어린이</p><span>오래도록, 마음에.</span></div>
<section className="album-section" id="album"><div className="section-heading"><div><p className="eyebrow">한 장 한 장, 다시 만나는 시간</p><h2>우리들의 졸업앨범</h2></div><p>빛바랜 종이 위에 남은<br/>그날의 모습 그대로.</p></div><div className="album-layout"><div className="album-index"><div className="index-heading">차 례 <span>{pages.length}장의 기억</span></div>{pages.map((p,i)=><button key={p[0]} onClick={()=>{setCurrent(i);setZoom(false)}} className={current===i?'selected':''} aria-current={current===i?'page':undefined}><span className="index-number">{String(i+1).padStart(2,'0')}</span><span>{p[1]}</span><ArrowUpRight size={16}/></button>)}</div><div className="album-sheet"><div className="sheet-top"><span>{pages[current][2]}</span><button onClick={()=>show(current)}><Maximize2 size={16}/> 크게 보기</button></div><button className="page-image" onClick={()=>show(current)} aria-label={`${pages[current][1]} 크게 보기`}><img src={photo(pages[current][0])} alt={pages[current][1]} loading="lazy"/></button><div className="page-controls"><button onClick={()=>move(-1)} disabled={current===0} aria-label="이전 앨범 페이지"><ArrowLeft size={20}/><span>이전 장</span></button><span aria-live="polite">{String(current+1).padStart(2,'0')} <i>/ {pages.length}</i></span><button onClick={()=>move(1)} disabled={current===pages.length-1} aria-label="다음 앨범 페이지"><span>다음 장</span><ArrowRight size={20}/></button></div></div></div></section>
<section className="moments" id="moments"><div className="section-heading"><div><p className="eyebrow">사진 속에 머문 날들</p><h2>그때 그 시절</h2></div><span className="handwritten">이 얼굴들, 기억나나요?</span></div><div className="memory-grid">{[[2,'학교, 그 이름만으로','늘 마음 한편에 남아 있는 곳.'],[8,'함께라서 즐거웠던 날','운동장에서도, 교실에서도.'],[4,'같은 교실, 같은 추억','선생님과 친구들이 함께한 시간.']].map(([idx,title,desc])=><button className="memory-card" key={String(idx)} onClick={()=>show(Number(idx))}><div className="memory-picture"><img src={photo(pages[Number(idx)][0])} alt={pages[Number(idx)][1]} loading="lazy"/></div><div className="memory-text"><span>기억 {String(Number(idx)+1).padStart(2,'0')}</span><h3>{title}</h3><p>{desc}</p><ArrowUpRight size={23}/></div></button>)}</div></section>
<section className="closing"><p>오랜 시간이 흘러도</p><h2>우리는, 월학의 친구들.</h2><span>1980학년도 · 월학국민학교 제26회 졸업기념</span></section></main>
<footer><a className="brand" href="#"><span className="seal">월학</span><span>월학국민학교<small>제26회 졸업생 추억 보관소</small></span></a><p>우리의 어린 날을 오래오래 간직합니다.</p><a href="#">맨 위로 ↑</a></footer>
<Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)setZoom(false)}}><DialogContent className="album-dialog" showCloseButton={false}><div className="viewer-top"><div><DialogTitle>{viewed[1]}</DialogTitle><DialogDescription>사진을 눌러 확대하거나 원래 크기로 돌아갈 수 있습니다.</DialogDescription></div><DialogClose className="close-viewer" aria-label="사진 닫기"><X size={24}/></DialogClose></div><div className={'viewer-image '+(zoom?'zoomed':'')}><button onClick={()=>setZoom(!zoom)} aria-label={zoom?'사진 축소':'사진 확대'}><img src={photo(viewed[0])} alt={viewed[1]}/></button></div>{!heroView&&<div className="page-controls"><button disabled={current===0} onClick={()=>move(-1)}><ArrowLeft size={20}/> 이전 장</button><span aria-live="polite">{current+1} / {pages.length}</span><button disabled={current===pages.length-1} onClick={()=>move(1)}>다음 장 <ArrowRight size={20}/></button></div>}</DialogContent></Dialog></>}
createRoot(document.getElementById('root')!).render(<App/>);

